name: health
description: "A new Health project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  lucide_icons: ^0.257.0
  supabase_flutter: ^2.9.0
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#FFFFFF"
  ios: true
  ios_content_mode: center
  fullscreen: true
  android: true
  web: false
  image_dark: "assets/images/logo.png"
  color_dark: "#000000" 
  android_gravity: center
  android_screen_orientation: portrait

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
